# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: send_server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='send_server.proto',
  package='send_server',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11send_server.proto\x12\x0bsend_server\"4\n\x10SendMessageParam\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"d\n\x18SendTemplateMessageParam\x12\x13\n\x0btemplate_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x11\n\tpage_path\x18\x03 \x01(\t\x12\x0f\n\x07id_json\x18\x04 \x01(\t\"\'\n\x14GetLawyerLetterParam\x12\x0f\n\x07\x62ill_id\x18\x01 \x01(\x05\">\n\x13SendMessageResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"F\n\x1bSendTemplateMessageResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"A\n\x16GetLawyerLetterRespnse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t2\xa6\x02\n\x0bSendService\x12P\n\x0bSendMessage\x12\x1d.send_server.SendMessageParam\x1a .send_server.SendMessageResponse\"\x00\x12h\n\x13SendTemplateMessage\x12%.send_server.SendTemplateMessageParam\x1a(.send_server.SendTemplateMessageResponse\"\x00\x12[\n\x0fGetLawyerletter\x12!.send_server.GetLawyerLetterParam\x1a#.send_server.GetLawyerLetterRespnse\"\x00\x62\x06proto3')
)




_SENDMESSAGEPARAM = _descriptor.Descriptor(
  name='SendMessageParam',
  full_name='send_server.SendMessageParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='send_server.SendMessageParam.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='send_server.SendMessageParam.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=86,
)


_SENDTEMPLATEMESSAGEPARAM = _descriptor.Descriptor(
  name='SendTemplateMessageParam',
  full_name='send_server.SendTemplateMessageParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='send_server.SendTemplateMessageParam.template_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='send_server.SendTemplateMessageParam.user_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_path', full_name='send_server.SendTemplateMessageParam.page_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_json', full_name='send_server.SendTemplateMessageParam.id_json', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=188,
)


_GETLAWYERLETTERPARAM = _descriptor.Descriptor(
  name='GetLawyerLetterParam',
  full_name='send_server.GetLawyerLetterParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bill_id', full_name='send_server.GetLawyerLetterParam.bill_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=229,
)


_SENDMESSAGERESPONSE = _descriptor.Descriptor(
  name='SendMessageResponse',
  full_name='send_server.SendMessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='send_server.SendMessageResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='send_server.SendMessageResponse.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='send_server.SendMessageResponse.data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=293,
)


_SENDTEMPLATEMESSAGERESPONSE = _descriptor.Descriptor(
  name='SendTemplateMessageResponse',
  full_name='send_server.SendTemplateMessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='send_server.SendTemplateMessageResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='send_server.SendTemplateMessageResponse.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='send_server.SendTemplateMessageResponse.data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=365,
)


_GETLAWYERLETTERRESPNSE = _descriptor.Descriptor(
  name='GetLawyerLetterRespnse',
  full_name='send_server.GetLawyerLetterRespnse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='send_server.GetLawyerLetterRespnse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='send_server.GetLawyerLetterRespnse.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='send_server.GetLawyerLetterRespnse.data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=432,
)

DESCRIPTOR.message_types_by_name['SendMessageParam'] = _SENDMESSAGEPARAM
DESCRIPTOR.message_types_by_name['SendTemplateMessageParam'] = _SENDTEMPLATEMESSAGEPARAM
DESCRIPTOR.message_types_by_name['GetLawyerLetterParam'] = _GETLAWYERLETTERPARAM
DESCRIPTOR.message_types_by_name['SendMessageResponse'] = _SENDMESSAGERESPONSE
DESCRIPTOR.message_types_by_name['SendTemplateMessageResponse'] = _SENDTEMPLATEMESSAGERESPONSE
DESCRIPTOR.message_types_by_name['GetLawyerLetterRespnse'] = _GETLAWYERLETTERRESPNSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendMessageParam = _reflection.GeneratedProtocolMessageType('SendMessageParam', (_message.Message,), dict(
  DESCRIPTOR = _SENDMESSAGEPARAM,
  __module__ = 'send_server_pb2'
  # @@protoc_insertion_point(class_scope:send_server.SendMessageParam)
  ))
_sym_db.RegisterMessage(SendMessageParam)

SendTemplateMessageParam = _reflection.GeneratedProtocolMessageType('SendTemplateMessageParam', (_message.Message,), dict(
  DESCRIPTOR = _SENDTEMPLATEMESSAGEPARAM,
  __module__ = 'send_server_pb2'
  # @@protoc_insertion_point(class_scope:send_server.SendTemplateMessageParam)
  ))
_sym_db.RegisterMessage(SendTemplateMessageParam)

GetLawyerLetterParam = _reflection.GeneratedProtocolMessageType('GetLawyerLetterParam', (_message.Message,), dict(
  DESCRIPTOR = _GETLAWYERLETTERPARAM,
  __module__ = 'send_server_pb2'
  # @@protoc_insertion_point(class_scope:send_server.GetLawyerLetterParam)
  ))
_sym_db.RegisterMessage(GetLawyerLetterParam)

SendMessageResponse = _reflection.GeneratedProtocolMessageType('SendMessageResponse', (_message.Message,), dict(
  DESCRIPTOR = _SENDMESSAGERESPONSE,
  __module__ = 'send_server_pb2'
  # @@protoc_insertion_point(class_scope:send_server.SendMessageResponse)
  ))
_sym_db.RegisterMessage(SendMessageResponse)

SendTemplateMessageResponse = _reflection.GeneratedProtocolMessageType('SendTemplateMessageResponse', (_message.Message,), dict(
  DESCRIPTOR = _SENDTEMPLATEMESSAGERESPONSE,
  __module__ = 'send_server_pb2'
  # @@protoc_insertion_point(class_scope:send_server.SendTemplateMessageResponse)
  ))
_sym_db.RegisterMessage(SendTemplateMessageResponse)

GetLawyerLetterRespnse = _reflection.GeneratedProtocolMessageType('GetLawyerLetterRespnse', (_message.Message,), dict(
  DESCRIPTOR = _GETLAWYERLETTERRESPNSE,
  __module__ = 'send_server_pb2'
  # @@protoc_insertion_point(class_scope:send_server.GetLawyerLetterRespnse)
  ))
_sym_db.RegisterMessage(GetLawyerLetterRespnse)



_SENDSERVICE = _descriptor.ServiceDescriptor(
  name='SendService',
  full_name='send_server.SendService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=435,
  serialized_end=729,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMessage',
    full_name='send_server.SendService.SendMessage',
    index=0,
    containing_service=None,
    input_type=_SENDMESSAGEPARAM,
    output_type=_SENDMESSAGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendTemplateMessage',
    full_name='send_server.SendService.SendTemplateMessage',
    index=1,
    containing_service=None,
    input_type=_SENDTEMPLATEMESSAGEPARAM,
    output_type=_SENDTEMPLATEMESSAGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLawyerletter',
    full_name='send_server.SendService.GetLawyerletter',
    index=2,
    containing_service=None,
    input_type=_GETLAWYERLETTERPARAM,
    output_type=_GETLAWYERLETTERRESPNSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENDSERVICE)

DESCRIPTOR.services_by_name['SendService'] = _SENDSERVICE

# @@protoc_insertion_point(module_scope)
